### PR TITLE
README.md: remove a lie

### PR DESCRIPTION
**Pull request by synt4x93**

### CODE REVIEW

**Comment by Fuseteam** [comment]
no comment on why this is closed? the JingPad is clearly not the first Linux tablet on the market, it has at least on predecessor: the BQ Aquaris M!0

**Comment by edwinhao-yawei** [comment]
It is first ARM-based consumer-level Linux Tablet.

--------------原始邮件--------------
发件人："Rahammetoela Toekiman ***@***.***&gt;;
发送时间：2021年6月9日(星期三) 晚上9:25
收件人："JingOS-team/JingOS" ***@***.***&gt;;
抄送："郝亚伟 ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [JingOS-team/JingOS] README.md: remove (#33)
-----------------------------------

 

 
no comment on why this is closed? the JingPad is clearly not the first Linux tablet on the market, it has at least on predecessor: the BQ Aquaris M!0

**Comment by Fuseteam** [comment]
@edwinhao-yawei the BQ Aquaris M10 __is__ an ARM-based consumer-level Linux Tablet

**Comment by nanu-c** [comment]
Gimp on BQ Aquaris M10 in 2016 https://www.youtube.com/watch?v=W6B6goxDPqM

**Pull request closed without merging**
